### ISSUE TITLE
文件类型错误

### ISSUE THREAD

**Issue by 1320494699** [Bian-Sh/Unity-Application-Auto-Builder#1]
![image](https://github.com/Bian-Sh/Unity-Application-Auto-Builder/assets/39151230/63c62271-bdcf-43ce-a921-266a39be7e47)
这是我修改过的！需要注意一下文件类型 原版打安卓的时候会导致导出 .exe文件

**Comment by Bian-Sh** [comment]
/

**Comment by Bian-Sh** [comment]
谢谢你愿意尝试并上报issue ，cheers！！！
